name: sync_helper_flutter
version: 1.9.1
environment:
  # The only constraint is on the Flutter framework version. Any Dart SDK
  # version compatible with the selected Flutter version will be used. A
  # minimal Dart SDK lower-bound is still required by pub.
  sdk: '>=3.9.2'
  flutter: '>=3.35.4'
dependencies:
  flutter:
    sdk: flutter
  http: 1.5.0
  sqlite_async: 0.12.1
  path_provider: 2.1.5
  path: ^1.9.0
  collection: ^1.18.0
  uuid: 4.5.1
  package_info_plus: 9.0.0
  # Sentry for error monitoring & logging â€“ SDK will be initialized by the
  # application that depends on this library. We only use the APIs.
  sentry_flutter: 9.6.0
  device_info_plus: 12.1.0
  # Optional Firebase Auth support
  firebase_auth: 6.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  test: any
executables:
  sync_generator:
  mock_sync_server:
